import React, { Component } from 'react';
import './DashNewsCard.css';
import $ from 'jquery';

export class DashNewsCard extends Component {
  handleCollapse(e) {
    const $card = $(e.target).parent().parent();
    const $header = $(e.target).parent();
    const $context = $card.find('.news-context');
    const initHeight = ($context[0].scrollHeight);
    $context.height(`${initHeight}px`);
    if ($card.hasClass('expanded')) {
      $card.removeClass('expanded');
      $card.addClass('collapsed');
      $context.height('0px');
    } else {
      $card.removeClass('collapsed');
      $card.addClass('expanded');
      $context.height(`${initHeight}px`);
    }
  }

  render() {
    return (
      <div>
        <div className="news-card col s12 trans-card z-depth-2 expanded">
          <div className="news-header blue darken-1">
            <div className="news-header-text col">
              Demo Information
		      </div>
            <div className="news-header-collapse right waves-effect waves-light" onClick={this.handleCollapse}>
              <i className="material-icons"></i>
            </div>
          </div>
          <div className="news-context">
            <div className="news-header">General Info</div>
            <div className="news-point"> Hey there! You've stumbled on my demo for my MemberDat project. Unfortunately, your changes will be deleted after a while though since it's deployed as Heroku app on the free plan. This means the database will reset every once in a while.
              <br>
              </br>
              <br>
              </br>
              Below you can find some names of parents/students that are generated by the app's seed for demo purposes if you want to try out the search function. Feel free to try adding some as well!
            </div>
            <div className="news-header">Parents</div>
            <div className="news-point">> The Mai, Andrew Nguyen, Michelle Bury, Chiwetel Ejiofor, Frank Reynolds</div>
            <div className="news-header">Students</div>
            <div className="news-point">> Simba Mai, Nhu Thao Ta, Coco Nguyen, Dennis Reynolds, Dee Reynolds, Letitia Wright, Camden Kirkland, Ian Mitchell, Brandon Gatlin, Mariam Sallam</div>
          </div>
        </div>
        <div className="news-card col s12 trans-card z-depth-2 expanded">
          <div className="news-header blue darken-1">
            <div className="news-header-text col">
              Newsfeed
		      </div>
            <div className="news-header-collapse right waves-effect waves-light" onClick={this.handleCollapse}>
              <i className="material-icons"></i>
            </div>
          </div>
          <div className="news-context">
            <div className="news-header">Upcoming Important Dates</div>
            <div className="news-point">1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed ipsum euismod, blandit dolor eget, venenatis quam. Nullam porttitor ante erat, in placerat augue scelerisque et.</div>
            <div className="news-header">New Updates</div>
            <div className="news-point">> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed ipsum euismod, blandit dolor eget, venenatis quam. Nullam porttitor ante erat, in placerat augue scelerisque et.</div>
            <div className="news-point">> Phasellus placerat nibh arcu, non iaculis ligula accumsan in. Praesent semper eleifend enim, ut volutpat tortor maximus sit amet.</div>
          </div>
        </div>
      </div>
    )
  }
}

export default DashNewsCard;